vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       user_img:
           uri_prefix: '/build/%user_img%'
           upload_destination: '%kernel.project_dir%/assets%user_img%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: true
           delete_on_update: false
           delete_on_remove: false
